# Generated by Django 5.2.12 on 2026-03-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('semanas_gestacion', models.IntegerField()),
                ('presion_arterial', models.CharField(max_length=20)),
                ('peso', models.FloatField()),
                ('glucosa', models.FloatField()),
                ('resultado', models.CharField(max_length=100)),
                ('nivel_riesgo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
