# Generated by Django 5.1.2 on 2026-07-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion_ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionia',
            name='resultado',
            field=models.TextField(),
        ),
    ]
