# Generated by Django 5.1.2 on 2026-07-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion_ia', '0002_alter_prediccionia_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionia',
            name='puntuacion_riesgo',
            field=models.IntegerField(default=0),
        ),
    ]
