# Generated by Django 5.2.12 on 2026-07-14 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_remove_paciente_tiene_prenatal_and_more'),
        ('prediccion_ia', '0004_prediccionia_campos_clinicos_completos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediccionia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Predicción IA', 'verbose_name_plural': 'Predicciones IA'},
        ),
        migrations.AlterField(
            model_name='prediccionia',
            name='edad',
            field=models.IntegerField(verbose_name='Edad (años)'),
        ),
        migrations.AlterField(
            model_name='prediccionia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de evaluación'),
        ),
        migrations.AlterField(
            model_name='prediccionia',
            name='glucosa',
            field=models.FloatField(verbose_name='Glucosa (mmol/L)'),
        ),
        migrations.AlterField(
            model_name='prediccionia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='prediccionia',
            name='peso',
            field=models.FloatField(verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='prediccionia',
            name='presion_arterial',
            field=models.CharField(max_length=20, verbose_name='Presión arterial'),
        ),
        migrations.AlterField(
            model_name='prediccionia',
            name='resultado',
            field=models.TextField(verbose_name='Resultado completo (JSON)'),
        ),
    ]
