# Generated by Django 5.2.12 on 2026-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion_ia', '0005_alter_prediccionia_options_alter_prediccionia_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediccionia',
            name='semanas_gestacion',
            field=models.IntegerField(default=0, verbose_name='Semanas de gestación'),
        ),
    ]
