# Generated by Django 5.2.12 on 2026-03-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_ultima_menstruacion', models.DateField()),
                ('fecha_probable_parto', models.DateField()),
            ],
        ),
    ]
