# Generated by Django 5.1.2 on 2026-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_datos_iniciales_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tiene_prenatal',
            field=models.BooleanField(default=False, help_text='Activado por la enfermera cuando la paciente general inicia control prenatal', verbose_name='Módulo prenatal activo'),
        ),
    ]
