# Generated by Django 5.2.12 on 2026-07-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_tiene_prenatal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='tiene_prenatal',
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_embarazo',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('SUSPENDIDO', 'Suspendido')], default='NINGUNO', help_text='Indica si la paciente tiene un embarazo en curso, finalizado, etc.', max_length=20, verbose_name='Estado del Embarazo'),
        ),
    ]
