# Generated by Django 5.2.12 on 2026-07-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_remove_paciente_tiene_prenatal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='mensaje_prenatal_visto',
            field=models.BooleanField(default=False, help_text='Indica si la paciente ya vio el mensaje de bienvenida al panel prenatal', verbose_name='Mensaje Prenatal Visto'),
        ),
    ]
