# Generated by Django 5.1.2 on 2026-07-10 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('motivo_consulta', models.TextField(verbose_name='Motivo de consulta')),
                ('antecedentes_personales', models.TextField(blank=True, default='', verbose_name='Antecedentes personales')),
                ('antecedentes_familiares', models.TextField(blank=True, default='', verbose_name='Antecedentes familiares')),
                ('antecedentes_alergicos', models.TextField(blank=True, default='', verbose_name='Antecedentes alérgicos')),
                ('antecedentes_quirurgicos', models.TextField(blank=True, default='', verbose_name='Antecedentes quirúrgicos')),
                ('antecedentes_obstetricos', models.TextField(blank=True, default='', verbose_name='Antecedentes obstétricos')),
                ('examen_fisico', models.TextField(blank=True, default='', verbose_name='Examen físico')),
                ('presion_arterial', models.CharField(blank=True, default='', max_length=20, verbose_name='Presión arterial (P/A)')),
                ('saturacion_oxigeno', models.IntegerField(blank=True, null=True, verbose_name='Saturación de oxígeno (%)')),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia cardíaca (lpm)')),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True, verbose_name='Frecuencia respiratoria (rpm)')),
                ('temperatura', models.FloatField(blank=True, null=True, verbose_name='Temperatura (°C)')),
                ('talla', models.FloatField(blank=True, null=True, verbose_name='Talla (m)')),
                ('peso', models.FloatField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('examenes_enviados', models.TextField(blank=True, default='', verbose_name='Exámenes enviados')),
                ('evolucion_enfermedad', models.TextField(blank=True, default='', verbose_name='Evolución de la enfermedad')),
                ('plan', models.TextField(blank=True, default='', verbose_name='Plan')),
                ('tratamiento', models.TextField(blank=True, default='', verbose_name='Tratamiento')),
                ('diagnostico_1_patologia', models.CharField(blank=True, default='', max_length=200, verbose_name='Patología 1')),
                ('diagnostico_1_cie10', models.CharField(blank=True, default='', max_length=20, verbose_name='CIE-10 1')),
                ('diagnostico_1_presuntivo', models.BooleanField(default=False, verbose_name='Presuntivo 1')),
                ('diagnostico_1_definitivo', models.BooleanField(default=False, verbose_name='Definitivo 1')),
                ('diagnostico_2_patologia', models.CharField(blank=True, default='', max_length=200, verbose_name='Patología 2')),
                ('diagnostico_2_cie10', models.CharField(blank=True, default='', max_length=20, verbose_name='CIE-10 2')),
                ('diagnostico_2_presuntivo', models.BooleanField(default=False, verbose_name='Presuntivo 2')),
                ('diagnostico_2_definitivo', models.BooleanField(default=False, verbose_name='Definitivo 2')),
                ('diagnostico_3_patologia', models.CharField(blank=True, default='', max_length=200, verbose_name='Patología 3')),
                ('diagnostico_3_cie10', models.CharField(blank=True, default='', max_length=20, verbose_name='CIE-10 3')),
                ('diagnostico_3_presuntivo', models.BooleanField(default=False, verbose_name='Presuntivo 3')),
                ('diagnostico_3_definitivo', models.BooleanField(default=False, verbose_name='Definitivo 3')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima cita')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_generales', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta General',
                'verbose_name_plural': 'Consultas Generales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('parto_natural', 'Parto Natural'), ('cesarea', 'Cesárea Programada'), ('induccion', 'Inducción del Parto')], default='parto_natural', max_length=20, verbose_name='Tipo')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('hora_programada', models.TimeField(verbose_name='Hora programada')),
                ('semanas_gestacion', models.IntegerField(blank=True, null=True, verbose_name='Semanas de gestación al momento')),
                ('lugar', models.CharField(blank=True, default='Zumedical — Centro Médico', max_length=200, verbose_name='Lugar / Sala')),
                ('indicaciones', models.TextField(blank=True, default='', verbose_name='Indicaciones para la paciente')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado'), ('reprogramado', 'Reprogramado')], default='programado', max_length=15, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos_programados', to=settings.AUTH_USER_MODEL, verbose_name='Médico responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones_parto', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Programación de Parto',
                'verbose_name_plural': 'Programaciones de Parto',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
