# Generated by Django 5.2.12 on 2026-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultageneral',
            name='proxima_cita_hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de próxima cita'),
        ),
    ]
