# Generated by Django 5.1.2 on 2026-07-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPrenatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.TextField()),
                ('palabras_clave', models.CharField(blank=True, default='', help_text='Separa las palabras clave con comas.', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ prenatal',
                'verbose_name_plural': 'FAQ prenatal',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(default='landing', max_length=50)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('pregunta_relacionada', models.CharField(blank=True, default='', max_length=200)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interacción del chatbot',
                'verbose_name_plural': 'Interacciones del chatbot',
                'ordering': ['-creada_en'],
            },
        ),
    ]
