# Generated by Django 5.2.12 on 2026-07-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_faqprenatal_faqchatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqchatbot',
            name='palabras_clave',
            field=models.CharField(blank=True, default='', help_text='Separa las palabras clave con comas (uso interno/búsqueda).', max_length=255),
        ),
    ]
