# Generated by Django 5.2.12 on 2026-06-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_paciente',
            field=models.CharField(blank=True, choices=[('prenatal', 'Prenatal'), ('general', 'General')], help_text='Solo aplica para usuarios con rol paciente', max_length=20, null=True),
        ),
    ]
