# Generated by Django 5.1.2 on 2026-07-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_datos_iniciales_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro / Prefiero no indicar')], help_text='Género de la paciente — solo pacientes femeninas pueden activar módulo prenatal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_paciente',
            field=models.CharField(blank=True, choices=[('prenatal', 'Prenatal'), ('general', 'General')], help_text='Tipo base de la cuenta — no restringe acceso a módulos adicionales', max_length=20, null=True),
        ),
    ]
