# Generated by Django 5.2.12 on 2026-07-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_genero_alter_usuario_tipo_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_paciente',
        ),
    ]
