# Generated by Django 5.2.12 on 2026-07-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_update_auditoria_cancelacion'),
        ('usuarios', '0006_remove_usuario_tipo_paciente'),
    ]

    operations = [
    ]
