# Generated by Django 5.2.12 on 2026-07-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_merge_20260722_1013'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logauditoria',
            new_name='usuarios_lo_fecha_a802c0_idx',
            old_name='usuarios_lo_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='logauditoria',
            new_name='usuarios_lo_usuario_c3cfe6_idx',
            old_name='usuarios_lo_usuario_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='logauditoria',
            new_name='usuarios_lo_accion_307aee_idx',
            old_name='usuarios_lo_accion_fecha_idx',
        ),
    ]
