# Generated by Django 5.2.12 on 2026-03-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPrenatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('semanas_gestacion', models.IntegerField()),
                ('presion_arterial', models.CharField(max_length=20)),
                ('peso', models.FloatField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
