# Generated by Django 5.2.12 on 2026-03-19 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_prenatal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlprenatal',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlprenatal',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
