# Generated by Django 5.1.2 on 2026-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_prenatal', '0003_datos_iniciales_control_prenatal'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlprenatal',
            name='altura',
            field=models.FloatField(default=1.6, help_text='En metros, ej: 1.62', verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='controlprenatal',
            name='complicaciones_previas',
            field=models.BooleanField(default=False, verbose_name='Complicaciones obstétricas previas'),
        ),
        migrations.AddField(
            model_name='controlprenatal',
            name='diabetes_gestacional',
            field=models.BooleanField(default=False, verbose_name='Diabetes gestacional'),
        ),
        migrations.AddField(
            model_name='controlprenatal',
            name='diabetes_preexistente',
            field=models.BooleanField(default=False, verbose_name='Diabetes preexistente'),
        ),
        migrations.AddField(
            model_name='controlprenatal',
            name='embarazos_previos',
            field=models.IntegerField(default=0, verbose_name='Embarazos previos'),
        ),
        migrations.AddField(
            model_name='controlprenatal',
            name='frecuencia_cardiaca',
            field=models.IntegerField(default=75, verbose_name='Frecuencia cardíaca (lpm)'),
        ),
        migrations.AddField(
            model_name='controlprenatal',
            name='glucosa',
            field=models.FloatField(default=90.0, help_text='Glucosa en sangre en mg/dL', verbose_name='Glucosa (mg/dL)'),
        ),
        migrations.AddField(
            model_name='controlprenatal',
            name='temperatura',
            field=models.FloatField(default=98.0, verbose_name='Temperatura (°F)'),
        ),
        migrations.AlterField(
            model_name='controlprenatal',
            name='observaciones',
            field=models.TextField(verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='controlprenatal',
            name='peso',
            field=models.FloatField(verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='controlprenatal',
            name='presion_arterial',
            field=models.CharField(max_length=20, verbose_name='Presión arterial'),
        ),
        migrations.AlterField(
            model_name='controlprenatal',
            name='semanas_gestacion',
            field=models.IntegerField(verbose_name='Semanas de gestación'),
        ),
    ]
