# Generated by Django 5.1.2 on 2026-07-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_prenatal', '0005_historiaclinica_campos_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlprenatal',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='antecedentes_familiares',
            field=models.TextField(blank=True, default='', help_text='Diabetes, hipertensión, gemelos, enfermedades hereditarias', verbose_name='Antecedentes familiares'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='antecedentes_obstetricos',
            field=models.TextField(blank=True, default='', help_text='Partos anteriores, abortos, cesáreas, fecha última regla', verbose_name='Antecedentes obstétricos y ginecológicos'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='antecedentes_personales',
            field=models.TextField(blank=True, default='', help_text='Enfermedades previas, cirugías, alergias, etc.', verbose_name='Antecedentes patológicos personales'),
        ),
    ]
