# Generated by Django 5.2.12 on 2026-06-16 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_options_cita_creado_alter_cita_medico_and_more'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.especialidad'),
        ),
    ]
