# Generated by Django 5.1.2 on 2026-07-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_datos_iniciales_citas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
