# Generated by Django 5.1.2 on 2026-07-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_add_estado_confirmada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo de cancelación de la cita', null=True),
        ),
    ]
